server:
  port: 8080
  servlet:
    context-path: /api.myservice.com/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommerce_web"
    username: root
    password: ngoduy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"